config/routes.rb
Rails.application.routes.draw do
  get 'welcome/homepage'
  root 'welcome#homepage'
  
  resources :item_bookings
  resources :event_bookings
  resources :items
  resources :suppliers
  resources :item_types
  resources :venues
  resources :billing_infos
  resources :clients
  resources :account_types

  match '/query', to: 'query#index', via: 'get'
  match '/query/queryOne', to: 'query#queryOne', via: 'get'
  match '/query/getQueryOne', to: 'query#getQueryOne', via: 'get'
  match '/query/queryTwo', to: 'query#queryTwo', via: 'get'
  match '/query/getQueryTwo', to: 'query#getQueryTwo', via: 'get'
  match '/query/queryThree', to: 'query#queryThree', via: 'get'
  match '/query/getQueryThree', to: 'query#getQueryThree', via: 'get'
  match '/query/queryFour', to: 'query#queryFour', via: 'get'
  match '/query/getQueryFour', to: 'query#getQueryFour', via: 'get'
  match '/query/queryFive', to: 'query#queryFive', via: 'get'
  match '/query/getQueryFive', to: 'query#getQueryFive', via: 'get'
  match '/query/querySix', to: 'query#querySix', via: 'get'
  match '/query/getQuerySix', to: 'query#getQuerySix', via: 'get'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/billing_info.rb
class BillingInfo < ApplicationRecord
end

app/controllers/billing_infos_controller.rb
class BillingInfosController < ApplicationController
  before_action :set_billing_info, only: [:show, :edit, :update, :destroy]

  # GET /billing_infos
  # GET /billing_infos.json
  def index
    @billing_infos = BillingInfo.all
    @clients = Client.all
  end

  # GET /billing_infos/1
  # GET /billing_infos/1.json
  def show
  end

  # GET /billing_infos/new
  def new
    @billing_info = BillingInfo.new
    @clients = Client.all
  end

  # GET /billing_infos/1/edit
  def edit
    @clients = Client.all
  end

  # POST /billing_infos
  # POST /billing_infos.json
  def create
    @billing_info = BillingInfo.new(billing_info_params)

    respond_to do |format|
      begin
        result = @billing_info.save
      rescue => e
        format.html { redirect_to @billing_info, notice: 'New entry could not be created due to invalid input or constraint violation.' }
        format.json { render :show, status: :unprocessable_entity, location: @billing_info }
      end

      if result
        format.html { redirect_to @billing_info, notice: 'Billing info was successfully created.' }
        format.json { render :show, status: :created, location: @billing_info }
      else
        format.html { render :new }
        format.json { render json: @billing_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /billing_infos/1
  # PATCH/PUT /billing_infos/1.json
  def update
    respond_to do |format|
      begin
        result = @billing_info.update(billing_info_params)
      rescue => e
        format.html { redirect_to @billing_info, notice: 'The change you wanted was rejected due to invalid input or constraint violation.' }
        format.json { render :show, status: :unprocessable_entity, location: @billing_info }
      end

      if result
        format.html { redirect_to @billing_info, notice: 'Billing info was successfully updated.' }
        format.json { render :show, status: :ok, location: @billing_info }
      else
        format.html { render :edit }
        format.json { render json: @billing_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /billing_infos/1
  # DELETE /billing_infos/1.json
  def destroy
    @billing_info.destroy
    respond_to do |format|
      format.html { redirect_to billing_infos_url, notice: 'Billing info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_billing_info
      @billing_info = BillingInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def billing_info_params
      params.require(:billing_info).permit(:client_id, :card_number, :name_on_card, :security_code, :month_expiry, :year_expiry)
    end
end

app/helpers/billing_infos_helper.rb
module BillingInfosHelper
end

app/views/billing_infos/_form.html.erb
<%= form_with(model: billing_info, local: true) do |form| %>
  <% if billing_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(billing_info.errors.count, "error") %> prohibited this billing_info from being saved:</h2>

      <ul>
      <% billing_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :client_id %>
    <%= form.collection_select :client_id, @clients, :id, :client_name %>
  </div>

  <div class="field">
    <%= form.label :card_number %>
    <%= form.text_field :card_number, id: :billing_info_card_number %>
  </div>

  <div class="field">
    <%= form.label :name_on_card %>
    <%= form.text_field :name_on_card, id: :billing_info_name_on_card %>
  </div>

  <div class="field">
    <%= form.label :security_code %>
    <%= form.text_field :security_code, id: :billing_info_security_code %>
  </div>

  <div class="field">
    <%= form.label :month_expiry %>
    <%= form.number_field :month_expiry, id: :billing_info_month_expiry %>
  </div>

  <div class="field">
    <%= form.label :year_expiry %>
    <%= form.number_field :year_expiry, id: :billing_info_year_expiry %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/billing_infos/edit.html.erb
<h1>Editing Billing Info</h1>

<%= render 'form', billing_info: @billing_info %>

<%= link_to 'Show', @billing_info %> |
<%= link_to 'Back', billing_infos_path %>

app/views/billing_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Billing Infos</h1>

<table id="datatable" class="table table-striped table-bordered" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Client</th>
      <th>Card number</th>
      <th>Name on card</th>
      <th>Security code</th>
      <th>Month expiry</th>
      <th>Year expiry</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @billing_infos.each do |billing_info| %>
      <tr>
        <td><%= @clients.where(id: billing_info.client_id).first.client_name %></td>
        <td><%= billing_info.card_number %></td>
        <td><%= billing_info.name_on_card %></td>
        <td><%= billing_info.security_code %></td>
        <td><%= billing_info.month_expiry %></td>
        <td><%= billing_info.year_expiry %></td>
        <td>
        <%= link_to 'Show', billing_info %>
        <%= link_to 'Edit', edit_billing_info_path(billing_info) %>
        <%= link_to 'Destroy', billing_info, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Billing Info', new_billing_info_path %>

app/views/billing_infos/new.html.erb
<h1>New Billing Info</h1>

<%= render 'form', billing_info: @billing_info %>

<%= link_to 'Back', billing_infos_path %>

app/views/billing_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client:</strong>
  <%= Client.all.where(id: @billing_info.client_id).first.client_name %>
</p>

<p>
  <strong>Card number:</strong>
  <%= @billing_info.card_number %>
</p>

<p>
  <strong>Name on card:</strong>
  <%= @billing_info.name_on_card %>
</p>

<p>
  <strong>Security code:</strong>
  <%= @billing_info.security_code %>
</p>

<p>
  <strong>Month expiry:</strong>
  <%= @billing_info.month_expiry %>
</p>

<p>
  <strong>Year expiry:</strong>
  <%= @billing_info.year_expiry %>
</p>

<%= link_to 'Edit', edit_billing_info_path(@billing_info) %> |
<%= link_to 'Back', billing_infos_path %>