config/routes.rb
Rails.application.routes.draw do
  get 'welcome/homepage'
  root 'welcome#homepage'
  
  resources :item_bookings
  resources :event_bookings
  resources :items
  resources :suppliers
  resources :item_types
  resources :venues
  resources :billing_infos
  resources :clients
  resources :account_types

  match '/query', to: 'query#index', via: 'get'
  match '/query/queryOne', to: 'query#queryOne', via: 'get'
  match '/query/getQueryOne', to: 'query#getQueryOne', via: 'get'
  match '/query/queryTwo', to: 'query#queryTwo', via: 'get'
  match '/query/getQueryTwo', to: 'query#getQueryTwo', via: 'get'
  match '/query/queryThree', to: 'query#queryThree', via: 'get'
  match '/query/getQueryThree', to: 'query#getQueryThree', via: 'get'
  match '/query/queryFour', to: 'query#queryFour', via: 'get'
  match '/query/getQueryFour', to: 'query#getQueryFour', via: 'get'
  match '/query/queryFive', to: 'query#queryFive', via: 'get'
  match '/query/getQueryFive', to: 'query#getQueryFive', via: 'get'
  match '/query/querySix', to: 'query#querySix', via: 'get'
  match '/query/getQuerySix', to: 'query#getQuerySix', via: 'get'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event_booking.rb
class EventBooking < ApplicationRecord
end

app/controllers/event_bookings_controller.rb
class EventBookingsController < ApplicationController
  before_action :set_event_booking, only: [:show, :edit, :update, :destroy]

  # GET /event_bookings
  # GET /event_bookings.json
  def index
    @event_bookings = EventBooking.all
    @clients = Client.all
    @venues = Venue.all
    @billing_infos = BillingInfo.all
  end

  # GET /event_bookings/1
  # GET /event_bookings/1.json
  def show
  end

  # GET /event_bookings/new
  def new
    @event_booking = EventBooking.new
    @clients = Client.all
    @venues = Venue.all
    @billingCards = BillingInfo.all
  end

  # GET /event_bookings/1/edit
  def edit
    @clients = Client.all
    @venues = Venue.all
    @billingCards = BillingInfo.all
  end

  # POST /event_bookings
  # POST /event_bookings.json
  def create
    @event_booking = EventBooking.new(event_booking_params)

    respond_to do |format|
      begin
        result = @event_booking.save
      rescue => e
        format.html { redirect_to @event_booking, notice: 'New entry could not be created due to invalid input or constraint violation.' }
        format.json { render :show, status: :unprocessable_entity, location: @event_booking }
      end

      if result
        format.html { redirect_to @event_booking, notice: 'Event booking was successfully created.' }
        format.json { render :show, status: :created, location: @event_booking }
      else
        format.html { render :new }
        format.json { render json: @event_booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_bookings/1
  # PATCH/PUT /event_bookings/1.json
  def update
    respond_to do |format|
      begin
        result = @event_booking.save
      rescue => e
        format.html { redirect_to @event_booking, notice: 'The change you wanted was rejected due to invalid input or constraint violation.' }
        format.json { render :show, status: :unprocessable_entity, location: @event_booking }
      end

      if result
        format.html { redirect_to @event_booking, notice: 'Event booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @event_booking }
      else
        format.html { render :edit }
        format.json { render json: @event_booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_bookings/1
  # DELETE /event_bookings/1.json
  def destroy
    @event_booking.destroy
    respond_to do |format|
      format.html { redirect_to event_bookings_url, notice: 'Event booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_booking
      @event_booking = EventBooking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_booking_params
      params.require(:event_booking).permit(:event_name, :client_id, :budget, :attendance, :venue_id, :start_time, :duration, :is_public, :notes, :actual_end_time, :amount, :billing_card, :billing_date)
    end
end

app/helpers/event_bookings_helper.rb
module EventBookingsHelper
end

app/views/event_bookings/_form.html.erb
<%= form_with(model: event_booking, local: true) do |form| %>
  <% if event_booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event_booking.errors.count, "error") %> prohibited this event_booking from being saved:</h2>

      <ul>
      <% event_booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :event_name %>
    <%= form.text_field :event_name, id: :event_booking_event_name %>
  </div>

  <div class="field">
    <%= form.label :client_id %>
    <%= form.collection_select :client_id, @clients, :id, :client_name %>
  </div>

  <div class="field">
    <%= form.label :budget %>
    <%= form.text_field :budget, id: :event_booking_budget %>
  </div>

  <div class="field">
    <%= form.label :attendance %>
    <%= form.number_field :attendance, id: :event_booking_attendance %>
  </div>

  <div class="field">
    <%= form.label :venue_id %>
    <%= form.collection_select :venue_id, @venues, :id, :venue_name %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time, id: :event_booking_start_time %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.text_field :duration, id: :event_booking_duration %>
  </div>

  <div class="field">
    <%= form.label :is_public %>
    <%= form.check_box :is_public, id: :event_booking_is_public %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_field :notes, id: :event_booking_notes %>
  </div>

  <div class="field">
    <%= form.label :actual_end_time %>
    <%= form.datetime_field :actual_end_time, id: :event_booking_actual_end_time %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount, id: :event_booking_amount %>
  </div>

  <div class="field">
    <%= form.label :billing_card %>
    <%= form.collection_select :billing_card, @billingCards, :id, :card_number %>
  </div>

  <div class="field">
    <%= form.label :billing_date %>
    <%= form.date_field :billing_date, id: :event_booking_billing_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/event_bookings/edit.html.erb
<h1>Editing Event Booking</h1>

<%= render 'form', event_booking: @event_booking %>

<%= link_to 'Show', @event_booking %> |
<%= link_to 'Back', event_bookings_path %>

app/views/event_bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Event Bookings</h1>

<table id="datatable" class="table table-striped table-bordered" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Event name</th>
      <th>Client</th>
      <th>Budget</th>
      <th>Attendance</th>
      <th>Venue</th>
      <th>Start time</th>
      <th>Duration</th>
      <th>Is public</th>
      <th>Notes</th>
      <th>Actual end time</th>
      <th>Amount</th>
      <th>Billing card</th>
      <th>Billing date</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @event_bookings.each do |event_booking| %>
      <tr>
        <td><%= event_booking.event_name %></td>
        <td><%= @clients.where(id: event_booking.client_id).first.client_name %></td>
        <td><%= event_booking.budget %></td>
        <td><%= event_booking.attendance %></td>
        <td><%= @venues.where(id: event_booking.venue_id).first.venue_name %></td>
        <td><%= event_booking.start_time.strftime("%m/%d/%Y %H:%M") %></td>
        <td><%= event_booking.duration %></td>
        <td><%= event_booking.is_public %></td>
        <td><%= event_booking.notes %></td>
        <td><%= event_booking.actual_end_time ? event_booking.actual_end_time.strftime("%m/%d/%Y %H:%M") : '' %></td>
        <td><%= event_booking.amount %></td>
        <td><%= @billing_infos.where(id: event_booking.billing_card).first.card_number %></td>
        <td><%= event_booking.billing_date ? event_booking.billing_date.strftime("%m/%d/%Y") : '' %></td>
        <td>
        <%= link_to 'Show', event_booking %>
        <%= link_to 'Edit', edit_event_booking_path(event_booking) %>
        <%= link_to 'Destroy', event_booking, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event Booking', new_event_booking_path %>

app/views/event_bookings/new.html.erb
<h1>New Event Booking</h1>

<%= render 'form', event_booking: @event_booking %>

<%= link_to 'Back', event_bookings_path %>

app/views/event_bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event name:</strong>
  <%= @event_booking.event_name %>
</p>

<p>
  <strong>Client:</strong>
  <%= Client.all.where(id: @event_booking.client_id).first.client_name %>
</p>

<p>
  <strong>Budget:</strong>
  <%= @event_booking.budget %>
</p>

<p>
  <strong>Attendance:</strong>
  <%= @event_booking.attendance %>
</p>

<p>
  <strong>Venue:</strong>
  <%= Venue.all.where(id: @event_booking.venue_id).first.venue_name %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @event_booking.start_time %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @event_booking.duration %>
</p>

<p>
  <strong>Is public:</strong>
  <%= @event_booking.is_public %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @event_booking.notes %>
</p>

<p>
  <strong>Actual end time:</strong>
  <%= @event_booking.actual_end_time %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @event_booking.amount %>
</p>

<p>
  <strong>Billing card:</strong>
  <%= BillingInfo.where(id: @event_booking.billing_card).first.card_number %>
</p>

<p>
  <strong>Billing date:</strong>
  <%= @event_booking.billing_date %>
</p>

<%= link_to 'Edit', edit_event_booking_path(@event_booking) %> |
<%= link_to 'Back', event_bookings_path %>