config/routes.rb
Rails.application.routes.draw do
  get 'welcome/homepage'
  root 'welcome#homepage'
  
  resources :item_bookings
  resources :event_bookings
  resources :items
  resources :suppliers
  resources :item_types
  resources :venues
  resources :billing_infos
  resources :clients
  resources :account_types

  match '/query', to: 'query#index', via: 'get'
  match '/query/queryOne', to: 'query#queryOne', via: 'get'
  match '/query/getQueryOne', to: 'query#getQueryOne', via: 'get'
  match '/query/queryTwo', to: 'query#queryTwo', via: 'get'
  match '/query/getQueryTwo', to: 'query#getQueryTwo', via: 'get'
  match '/query/queryThree', to: 'query#queryThree', via: 'get'
  match '/query/getQueryThree', to: 'query#getQueryThree', via: 'get'
  match '/query/queryFour', to: 'query#queryFour', via: 'get'
  match '/query/getQueryFour', to: 'query#getQueryFour', via: 'get'
  match '/query/queryFive', to: 'query#queryFive', via: 'get'
  match '/query/getQueryFive', to: 'query#getQueryFive', via: 'get'
  match '/query/querySix', to: 'query#querySix', via: 'get'
  match '/query/getQuerySix', to: 'query#getQuerySix', via: 'get'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item_booking.rb
class ItemBooking < ApplicationRecord
end

app/controllers/item_bookings_controller.rb
class ItemBookingsController < ApplicationController
  before_action :set_item_booking, only: [:show, :edit, :update, :destroy]

  # GET /item_bookings
  # GET /item_bookings.json
  def index
    @item_bookings = ItemBooking.all
    @items = Item.all
    @events = EventBooking.all
  end

  # GET /item_bookings/1
  # GET /item_bookings/1.json
  def show
  end

  # GET /item_bookings/new
  def new
    @item_booking = ItemBooking.new
    @events = EventBooking.all
    @items = Item.all
  end

  # GET /item_bookings/1/edit
  def edit
    @events = EventBooking.all
    @items = Item.all
  end

  # POST /item_bookings
  # POST /item_bookings.json
  def create
    @item_booking = ItemBooking.new(item_booking_params)

    respond_to do |format|
      begin
        result = @item_booking.save
      rescue => e
        format.html { redirect_to @item_booking, notice: 'New entry could not be created due to invalid input or constraint violation.' }
        format.json { render :show, status: :unprocessable_entity, location: @item_booking }
      end

      if 
        format.html { redirect_to @item_booking, notice: 'Item booking was successfully created.' }
        format.json { render :show, status: :created, location: @item_booking }
      else
        format.html { render :new }
        format.json { render json: @item_booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /item_bookings/1
  # PATCH/PUT /item_bookings/1.json
  def update
    respond_to do |format|
      begin
        result = @item_booking.update(item_booking_params)
      rescue => e
        format.html { redirect_to @item_booking, notice: 'The change you wanted was rejected due to invalid input or constraint violation.' }
        format.json { render :show, status: :unprocessable_entity, location: @item_booking }
      end

      if result
        format.html { redirect_to @item_booking, notice: 'Item booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @item_booking }
      else
        format.html { render :edit }
        format.json { render json: @item_booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /item_bookings/1
  # DELETE /item_bookings/1.json
  def destroy
    @item_booking.destroy
    respond_to do |format|
      format.html { redirect_to item_bookings_url, notice: 'Item booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item_booking
      @item_booking = ItemBooking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_booking_params
      params.require(:item_booking).permit(:event_id, :item_id, :quantity, :notes)
    end
end

app/helpers/item_bookings_helper.rb
module ItemBookingsHelper
end

app/views/item_bookings/_form.html.erb
<%= form_with(model: item_booking, local: true) do |form| %>
  <% if item_booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item_booking.errors.count, "error") %> prohibited this item_booking from being saved:</h2>

      <ul>
      <% item_booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :event_id %>
    <%= form.collection_select :event_id, @events, :id, :event_name %>
  </div>

  <div class="field">
    <%= form.label :item_id %>
    <%= form.collection_select :item_id, @items, :id, :item_name %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.text_field :quantity, id: :item_booking_quantity %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_field :notes, id: :item_booking_notes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/item_bookings/edit.html.erb
<h1>Editing Item Booking</h1>

<%= render 'form', item_booking: @item_booking %>

<%= link_to 'Show', @item_booking %> |
<%= link_to 'Back', item_bookings_path %>

app/views/item_bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Item Bookings</h1>

<table id="datatable" class="table table-striped table-bordered" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Event</th>
      <th>Item</th>
      <th>Quantity</th>
      <th>Notes</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @item_bookings.each do |item_booking| %>
      <tr>
        <td><%= @events.where(id: item_booking.event_id).first.event_name %></td>
        <td><%= @items.where(id: item_booking.item_id).first.item_name %></td>
        <td><%= item_booking.quantity %></td>
        <td><%= item_booking.notes %></td>
        <td>
        <%= link_to 'Show', item_booking %>
        <%= link_to 'Edit', edit_item_booking_path(item_booking) %>
        <%= link_to 'Destroy', item_booking, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item Booking', new_item_booking_path %>

app/views/item_bookings/new.html.erb
<h1>New Item Booking</h1>

<%= render 'form', item_booking: @item_booking %>

<%= link_to 'Back', item_bookings_path %>

app/views/item_bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event:</strong>
  <%= EventBooking.all.where(id: @item_booking.event_id).first.event_name %>
</p>

<p>
  <strong>Item:</strong>
  <%= Item.all.where(id: @item_booking.item_id).first.item_name %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @item_booking.quantity %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @item_booking.notes %>
</p>

<%= link_to 'Edit', edit_item_booking_path(@item_booking) %> |
<%= link_to 'Back', item_bookings_path %>