config/routes.rb
Rails.application.routes.draw do
  get 'welcome/homepage'
  root 'welcome#homepage'
  
  resources :item_bookings
  resources :event_bookings
  resources :items
  resources :suppliers
  resources :item_types
  resources :venues
  resources :billing_infos
  resources :clients
  resources :account_types

  match '/query', to: 'query#index', via: 'get'
  match '/query/queryOne', to: 'query#queryOne', via: 'get'
  match '/query/getQueryOne', to: 'query#getQueryOne', via: 'get'
  match '/query/queryTwo', to: 'query#queryTwo', via: 'get'
  match '/query/getQueryTwo', to: 'query#getQueryTwo', via: 'get'
  match '/query/queryThree', to: 'query#queryThree', via: 'get'
  match '/query/getQueryThree', to: 'query#getQueryThree', via: 'get'
  match '/query/queryFour', to: 'query#queryFour', via: 'get'
  match '/query/getQueryFour', to: 'query#getQueryFour', via: 'get'
  match '/query/queryFive', to: 'query#queryFive', via: 'get'
  match '/query/getQueryFive', to: 'query#getQueryFive', via: 'get'
  match '/query/querySix', to: 'query#querySix', via: 'get'
  match '/query/getQuerySix', to: 'query#getQuerySix', via: 'get'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/item_type.rb
class ItemType < ApplicationRecord
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
    @item_types = ItemType.all
    @suppliers = Supplier.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
    @itemTypes = ItemType.all
    @suppliers = Supplier.all
  end

  # GET /items/1/edit
  def edit
    @itemTypes = ItemType.all
    @suppliers = Supplier.all
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:item_name, :item_type_id, :supplier_id, :pricing)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :item_name %>
    <%= form.text_field :item_name, id: :item_item_name %>
  </div>

  <div class="field">
    <%= form.label :item_type_id %>
    <%= form.collection_select :item_type_id, @itemTypes, :id, :item_type_name %>
  </div>

  <div class="field">
    <%= form.label :supplier_id %>
    <%= form.collection_select :supplier_id, @suppliers, :id, :supplier_name %>
  </div>

  <div class="field">
    <%= form.label :pricing %>
    <%= form.text_field :pricing, id: :item_pricing %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table id="datatable" class="table table-striped table-bordered" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Item name</th>
      <th>Item type</th>
      <th>Supplier</th>
      <th>Pricing</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.item_name %></td>
        <td><%= @item_types.where(id: item.item_type_id).first.item_type_name %></td>
        <td><%= @suppliers.where(id: item.supplier_id).first.supplier_name %></td>
        <td><%= item.pricing %></td>
        <td>
        <%= link_to 'Show', item %>
        <%= link_to 'Edit', edit_item_path(item) %>
        <%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item name:</strong>
  <%= @item.item_name %>
</p>

<p>
  <strong>Item type:</strong>
  <%= ItemType.where(id: @item.item_type_id).first.item_type_name %>
</p>

<p>
  <strong>Supplier:</strong>
  <%= Supplier.all.where(id: @item.supplier_id).first.supplier_name %>
</p>

<p>
  <strong>Pricing:</strong>
  <%= @item.pricing %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>